feat: implement patient scope; remove system & launch scopes
awslabs/fhir-works-on-aws-authz-smart pull request #13
Opened 2021-01-09 03:45 UTC by rsmayda

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-09 03:47 UTC, rsmayda commented on src/regExpressions.test.ts
> -        for (let i = 0; i < testCases.length; i += 1) {
removing this `for`

2021-01-09 04:01 UTC, rsmayda commented on src/smartHandler.ts
> -                if (['patient', 'user', 'system'].includes(smartScope.scopeType)) {
removed this `if`

2021-01-09 04:01 UTC, rsmayda commented on src/smartHandler.ts
> -                        if (['patient', 'user', 'system'].includes(clinicalSmartScope.scopeType)) {
removed this `if`

2021-01-11 17:39 UTC, nguyen102 submitted a review, later dismissed
Great job! This looks good! One small commet about renaming filterScopes

2021-01-11 17:39 UTC, nguyen102 commented on src/smartScopeHelper.ts
> +export function filterScopes(
nitpick: Can we rename this to something like `filterOutUnusableScope`?

2021-01-11 17:59 UTC, carvantes commented on src/smartHandler.test.ts
> +        decode.mockReturnValue(<{ [key: string]: any }>decodedAccessToken);
Why are we mocking this? I think it's better to just encode `decodedAccessToken` into a JWT with `jwt.sign`

https://www.npmjs.com/package/jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback

2021-01-11 18:53 UTC, carvantes commented on src/regExpressions.test.ts
> +        ['127.0.0.1/project_name', 'Patient', 'id', true, false],
IMO using tests arrays to branch test assertions is a bad practice, it is hard to understand what all those `true` and `false` represent. 

I think it's better to keep the array focused on test data only, with the assumption that it's just different test data that goes through the same test code.

here `hasHostname` can be derived from `hostname`, and it'd be better to have 2 test suites, on for success and one for failure instead of relying on `isSuccess` (also, all tests have `isSuccess=true`, so `isSuccess` is useless)

2021-01-11 19:20 UTC, carvantes commented on src/smartScopeHelper.test.ts
> +        clonedScopeRule[scopeType].read = ['search-system'];
I think it's best to avoid using `clone` here. I think it was a bad idea to add that function to the interface package and we should eventually remove it.

A quick fix would be to use a function that generates the empty scope rule instead:
```js
const emptyScopeRule = () => ({
    patient: {
        read: [],
        write: [],
    },
    user: {
        read: [],
        write: [],
    },
});
```

2021-01-11 19:25 UTC, carvantes commented on src/smartScopeHelper.test.ts
> +        clonedScopeRule.patient.read = ['read'];
It's probably easier and clearer to just do:
```js
const scopeRule = {
    patient: {
        read: ['read'],
        write: [],
    },
    user: {
        read: ['read'],
        write: [],
    },
}
```

btw, I just realized that the scope rule is weird in that you can have `patient.write['read']` and `patient.read['write']`. What does it mean to have "write" permissions on the "read" operation?

2021-01-11 19:33 UTC, carvantes commented on src/smartConfig.ts
> + *          read: allReadOperations,
what does `allReadOperations` means? I think that the `@example` should be self-contained

2021-01-11 19:34 UTC, carvantes commented on src/smartAuthorizationHelper.test.ts
> +    test('valid fhirResource;; With default hostname', () => {
typo: `;;`

2021-01-11 19:40 UTC, carvantes commented on src/smartAuthorizationHelper.ts
> +        }
I think that we should avoid disabling eslint rules unless we have a strong reason to do so. 
```suggestion
        const { resourceType, id } = match.groups!;
        const hostname = match.groups!.hostname ?? defaultHostname;
```

2021-01-11 19:52 UTC, carvantes requested changes

2021-01-11 19:52 UTC, carvantes commented on src/smartAuthorizationHelper.ts
> +export const FHIR_RESOURCE_REGEX = /(?<hostname>^(http|https):\/\/([A-Za-z0-9\-\\.:%$_]*\/)+)?(?<resourceType>[A-Z][a-zA-Z]+)\/(?<id>[A-Za-z0-9\-.]+)$/;
looks like the `^` anchor is misplaced. This regex matches `SomeRandomPrefixPatient/id`

2021-01-11 19:59 UTC, carvantes commented on src/smartAuthorizationHelper.ts
> +export function authorizeResource(fhirResource: FhirResource, resource: any, apiUrl: string): boolean {
nit: rename to something like `hasReferenceToResource`. This function doesn't really "authorizes" something

2021-01-11 20:04 UTC, carvantes commented on src/smartAuthorizationHelper.ts
> +export function authorizeResource(fhirResource: FhirResource, resource: any, apiUrl: string): boolean {
Actually this rename is not trivial since this function has the weird condition that does not deal with references:
```
if (resourceType === 'Practitioner') {
        return true;
    }
```

Still, I believe that the above condition can be removed since it is already checked outside this function as part of the `this.adminAccessTypes.includes` check

2021-01-11 20:08 UTC, rsmayda commented on src/smartHandler.test.ts
> +        decode.mockReturnValue(<{ [key: string]: any }>decodedAccessToken);
mocking it as it makes test generation easier, previously we just used a raw opaque JWT token, now we can use objects

Using jwt.sign is an option but it also ties this unit test to jwt (which isn't necessarily bad). I don't have a strong preference but would prefer to leave it as is as @nguyen102 is moving the code from using decode -> verify and that has probably a better use-case for using this jwt.sign approach

2021-01-11 20:11 UTC, rsmayda commented on src/smartScopeHelper.test.ts
> +        clonedScopeRule.patient.read = ['read'];
> What does it mean to have "write" permissions on the "read" operation?

Yep that is right we could limit it via using type mapping -- I think changing the type will make more sense

2021-01-11 21:41 UTC, nguyen102 commented on src/smartHandler.test.ts
> +        decode.mockReturnValue(<{ [key: string]: any }>decodedAccessToken);
Given this use case, I don't see any issue with mocking. 

It's simpler than using signing. To use `jwt.sign` correctly, we would need to sign using the `RS256` algorithm instead of the default `HS256` algorithm. The `RS256` algorithm requires a private key, which we need to store and import into this test.

If mocking accomplish the same objective, which is to make the payload of the JWT easy to read, we should just use mocking.

2021-01-11 21:41 UTC, rsmayda commented on src/regExpressions.test.ts
> +        ['127.0.0.1/project_name', 'Patient', 'id', true, false],
cleaned up in this file

2021-01-11 21:47 UTC, rsmayda commented on src/smartScopeHelper.test.ts
> +        clonedScopeRule[scopeType].read = ['search-system'];
updated!

2021-01-11 22:04 UTC, rsmayda commented on src/smartConfig.ts
> + *          read: allReadOperations,
fixed

2021-01-11 22:10 UTC, rsmayda commented on src/smartAuthorizationHelper.ts
> +        }
fixed

2021-01-11 22:13 UTC, rsmayda commented on src/smartAuthorizationHelper.ts
> +export const FHIR_RESOURCE_REGEX = /(?<hostname>^(http|https):\/\/([A-Za-z0-9\-\\.:%$_]*\/)+)?(?<resourceType>[A-Z][a-zA-Z]+)\/(?<id>[A-Za-z0-9\-.]+)$/;
For FHIR_RESOURCE_REGEX  we are okay with using a default hostname (if one is not provided), but if one is provided it should be legal ie:
- Good:
  - Patient/id
  - http://new.api.com/Patient/id
- Bad:
  - Fake things/Patient/id

I did have to move `^` but do note the `?` making hostname part optional

2021-01-11 22:18 UTC, rsmayda commented on src/smartAuthorizationHelper.ts
> +export function authorizeResource(fhirResource: FhirResource, resource: any, apiUrl: string): boolean {
fixed

2021-01-11 22:58 UTC, rsmayda commented on src/smartAuthorizationHelper.test.ts
> +    test('valid fhirResource;; With default hostname', () => {
fixed

2021-01-11 23:41 UTC, carvantes commented on src/regExpressions.test.ts
> +    test.each(testCases)('CASE: %p/%p.%p; expect: %p', async (scopeType, scopeResourceType, accessType) => {
You need to update the test names as well. It still has 4 instances of `%p`

2021-01-11 23:42 UTC, carvantes commented on src/regExpressions.test.ts
> +    test.each(testCases)('CASE: %p%p/%p; expect: %p', async (hostname, resourceType, id) => {
update test names as well

2021-01-11 23:57 UTC, carvantes commented on src/smartHandler.test.ts
> +        decode.mockReturnValue(<{ [key: string]: any }>decodedAccessToken);
yeah, the timing of these changes make it trickier to coordinate. I agree that using real JWT tokens here can be cumbersome with the switch to asymmetric keys. I leave it up to you 2 to decide.

IMO mocking is ok, but mocking `jsonwebtoken.decode` is too low level. It'd be better to mock an higher level abstraction like `smartAuthorizationHelper.verifyJwtToken` but that's on Tim's new PR so it's probably ok to leave as is.

2021-01-12 18:27 UTC, carvantes approved these changes
looks good. Just one more comment regarding `adminAccessTypes`. It's about existing code so I'm not blocking on it.

2021-01-12 18:27 UTC, carvantes commented on src/smartAuthorizationHelper.ts
>      }
should this be updated to use the `SMARTHandler.adminAccessTypes` instead of hardcoding `'Practitioner'`?

I'm actually not 100% sure about what `adminAccessTypes` does

2021-01-12 19:45 UTC, merged