feat: support string array in OAuth aud claim
awslabs/fhir-works-on-aws-authz-smart pull request #2
Opened 2020-11-10 14:49 UTC by emilhdiaz

Description of changes:

As per [rfc7519](https://tools.ietf.org/html/rfc7519#section-4.1.3): 

> In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.

This change allows the `aud` claim in the `access_token` JWT to be either a `string` or `string[]` (string array). 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-10 19:04 UTC, rsmayda commented on src/smartConfig.ts
> +    expectedAudValue: string | string[];
This value signifies what we should look for in the `aud` claim. We know that the `aud` claim _must_ contain this fhir server url

So I think it makes sense for this to be a single string

2020-11-10 19:04 UTC, rsmayda commented on src/smartHandler.ts
> +        if (!isEqual(this.config.expectedIssValue, iss) || !isEqual(this.config.expectedAudValue, aud)) {
`aud` here could be an array since the access_token could be giving access to many EHRs

2020-11-10 21:50 UTC, emilhdiaz commented on src/smartConfig.ts
> +    expectedAudValue: string | string[];
@rsmayda good point. So would it make more sense to keep `expectedAudValue` here as a string, but perform a string match OR array lookup in the handler?

2020-11-10 22:34 UTC, rsmayda commented on src/smartConfig.ts
> +    expectedAudValue: string | string[];
Yep that is what I am thinking!

2020-11-11 02:16 UTC, emilhdiaz commented on src/smartConfig.ts
> +    expectedAudValue: string | string[];
Makes sense, I reverted the SMARTConfig changes and instead updated the `aud` check to assume either string or array.

2020-11-11 02:18 UTC, emilhdiaz commented on src/smartHandler.ts
> +        if (!isEqual(this.config.expectedIssValue, iss) || !isEqual(this.config.expectedAudValue, aud)) {
I reverted the `isEqual()` calls here given I no longer need to compare the equality of array.

2020-11-11 14:17 UTC, rsmayda approved these changes
Looks good!

2020-11-11 14:18 UTC, rsmayda requested changes
Whoops forgot to ask can you add a test case for when aud is an array?

2020-11-11 16:39 UTC, emilhdiaz commented
Ah yep, just did. It's my first time writing unit tests in jest, so hopefully I implemented the tests correctly.

2020-11-11 19:09 UTC, rsmayda approved these changes
Unit tests look good! Thanks

2020-11-12 17:23 UTC, merged