feat: update system export to only allow system scope by default
awslabs/fhir-works-on-aws-authz-smart pull request #60
Opened 2021-09-02 20:17 UTC by Bingjiling

Issue #, if available:

Description of changes:

* Update system export to only allow system scope by default
* Add config value to allow user scope 
* Updated unit tests 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-02 20:20 UTC, ssvegaraju submitted a review, later dismissed
Looks good to me

2021-09-08 15:02 UTC, rsmayda requested changes

2021-09-08 15:02 UTC, rsmayda commented on src/smartScopeHelper.ts
> +            process.env.ALLOW_USER_SCOPE_FOR_SYSTEM_EXPORT === 'true'
Could this be a constructor argument and not an env variable?

2021-09-10 17:33 UTC, Bingjiling commented on src/smartScopeHelper.ts
> +            process.env.ALLOW_USER_SCOPE_FOR_SYSTEM_EXPORT === 'true'
Yes! That'll make it a lot simpler.

2021-09-13 21:32 UTC, rsmayda approved these changes

2021-09-14 13:45 UTC, merged