fix: remove filtered responses from total count
awslabs/fhir-works-on-aws-authz-smart pull request #63
Opened 2021-09-09 04:10 UTC by ssvegaraju

Issue #, if available:
#55
Description of changes:
Updated the `authorizeAndFilterReadResponse` method to correctly update the total number of results in a bundle when filtering unauthorized resources.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-09 14:41 UTC, rsmayda commented on src/smartHandler.ts
> +            }
Do you need this `if` block?

2021-09-09 14:41 UTC, rsmayda commented on src/smartHandler.ts
> +            const totalNumEntriesAfterFilter: number =
Can you add tests for this?

2021-09-10 07:13 UTC, ssvegaraju commented on src/smartHandler.ts
> +            }
Some of the tests were failing to due `readResponse.total` being NaN, but I changed the if condition to be clearer on that.

2021-09-10 07:27 UTC, ssvegaraju commented on src/smartHandler.ts
> +            const totalNumEntriesAfterFilter: number =
I added a few tests for this but realized that they were redundant as we already have tests filtering results from the searches both partially and completely.

2021-09-10 13:59 UTC, rsmayda commented on src/smartHandler.ts
> +            const totalNumEntriesAfterFilter: number =
It looks like the existing tests are not taking into account the total: https://github.com/awslabs/fhir-works-on-aws-authz-smart/blob/mainline/src/smartHandler.test.ts#L730

Could you change the existing tests to look more of what the router sends in (i.e. include the `total`):
https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/bundle/bundleGenerator.ts#L25

2021-09-10 14:02 UTC, rsmayda requested changes

2021-09-10 14:02 UTC, rsmayda commented on src/smartHandler.ts
> +            }
The router should always send the total: https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/bundle/bundleGenerator.ts#L32

but if it doesn't lets set it to the existing length:

```suggestion
            if (!readResponse.total) {
                readResponse.total = entries.length;
            } else {
                readResponse.total -= readResponse.entry.length - entries.length;
            }
```

2021-09-13 04:28 UTC, ssvegaraju commented on src/smartHandler.ts
> +            const totalNumEntriesAfterFilter: number =
Updated all of the tests for this module to include totals as an adjusted parameter similar to how `entry` was processed!

2021-09-13 04:30 UTC, ssvegaraju commented on src/smartHandler.ts
> +            }
Implemented this change, but did it a bit differently as directly modifying `readResponse.total` proved to be a bad idea due to the fact that the test runs `authorizeAndFilterReadResponse` twice per filter (one with the FhirServiceBaseUrl and one without), and the request would end up modified from the previous call. Instead, passing it back as part of the spread operator worked.

2021-09-13 15:40 UTC, rsmayda requested changes

2021-09-13 15:40 UTC, rsmayda commented on src/smartHandler.test.ts
> +        total: 5,
`searchSomeEntitiesMatch` should have a differing output total looks like total should be set to 3? I don't see that being tested - maybe I missed it though?

this is the case name: `SEARCH: user scope; Patient's history results are filtered to only contain valid entries`

2021-09-13 15:43 UTC, ssvegaraju commented on src/smartHandler.test.ts
> +        total: 5,
Yeah, the total is actually 3 because it uses `searchAllEntitiesMatch` as the `respBody` in the test cases (the 4th parameter in that case definition on line 974). This has a total of 3.

2021-09-13 17:03 UTC, rsmayda commented on src/smartHandler.test.ts
> +        total: 5,
Thank you for explaining!

2021-09-13 17:03 UTC, rsmayda approved these changes

2021-09-13 17:13 UTC, merged